#ifndef GSETTINGDEFINES_H
#define GSETTINGDEFINES_H

#define GSETTING_DEFNOTEFILE_CFGSTR "DefaultNoteFile"
#define GSETTING_DEFNOTEFILE_DEFAULT ""

#define GSETTING_AUTOSAVE_CFGSTR "Autosave"
#define GSETTING_AUTOSAVE_DEFAULT true

#define GSETTING_SHOWTIPS_CFGSTR "ShowTips"
#define GSETTING_SHOWTIPS_DEFAULT true

#define GSETTING_SAVEWINSTATE_CFGSTR "SaveWinState"
#define GSETTING_SAVEWINSTATE_DEFAULT true


#endif // GSETTINGDEFINES_H
